[tool.black]
line-length = 100
target-version = ["py312"]
exclude = "(venv|\\.venv)"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["venv", ".venv"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "ASYNC"]
ignore = ["E203", "E266"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
