#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-venv
  - python3-pip
  - git

users:
  - name: timeflow
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
      - # <INSERT_SSH_KEY>

write_files:
  - path: /etc/systemd/system/timeflow.service
    permissions: '0644'
    content: |
      [Unit]
      Description=TimeFlow Bot
      After=network-online.target
      Wants=network-online.target
      [Service]
      Type=simple
      User=timeflow
      WorkingDirectory=/opt/TimeFLow
      EnvironmentFile=/opt/TimeFLow/.env
      ExecStart=/opt/TimeFLow/venv/bin/python3 /opt/TimeFLow/main.py
      Restart=always
      RestartSec=5
      Environment=PYTHONUNBUFFERED=1
      [Install]
      WantedBy=multi-user.target
  - path: /etc/rc.local
    permissions: '0755'
    content: |
      #!/bin/bash
      if [ -s /opt/TimeFLow/.env ]; then
        systemctl restart timeflow
      fi
      exit 0

runcmd:
  - mkdir -p /opt/TimeFLow
  - chown -R timeflow:timeflow /opt/TimeFLow
  - sudo -u timeflow git clone <REPO_URL> /opt/TimeFLow
  - cd /opt/TimeFLow && sudo -u timeflow python3 -m venv venv
  - cd /opt/TimeFLow && sudo -u timeflow /opt/TimeFLow/venv/bin/pip install --upgrade pip
  - cd /opt/TimeFLow && sudo -u timeflow /opt/TimeFLow/venv/bin/pip install -r requirements.txt
  - touch /opt/TimeFLow/.env
  - touch /opt/TimeFLow/service-account.json
  - chmod 600 /opt/TimeFLow/service-account.json
  - systemctl daemon-reload
  - systemctl enable timeflow
  - systemctl start timeflow
