name: CI
on:
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore: [ "docs/**", "**/*.md" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt
      - name: Ruff
        run: ruff check .
      - name: Black (check)
        run: black --check .
      - name: Pytest
        run: pytest -q
